//
//  SampleCode.swift
//  LayoutArchitect
//
//  Created by Brian Thomas on 7/14/14.
//  Copyright (c) 2014 banditcastle. All rights reserved.
//

import UIKit
import Architect

class SampleController: UIViewController {
  
  @IBOutlet var aView : UIView?
  var whiteView: UIView!
  var greenView: UIView!
  var yellowView: UIView!
  var label: UILabel!
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    //        Architect.printDocumentation()
    //        Blueprint.printDocumentation()
    
    whiteView = Architect.custom(ColorView(color: UIColor.whiteColor()), inView: aView!) {
      Constrain.inset($0, with: [.Top: 40, .Left: 0, .Bottom: 10, .Right: 20])
    }
    
    greenView = Architect.custom(ColorView(color: UIColor.greenColor()), inView: whiteView) {
      Grunt.size($0, withExtendedOptions: [.Width: (.Equal, 20, .Required)])
      Grunt.inset($0, with: [.Top: 0, .Left: 0, .Bottom: 0])
    }
    
    yellowView = Architect.custom(ColorView(color: UIColor.yellowColor()), inView: self.view) { [unowned self] in
      Grunt.center($0, from: self.view, with: [.X: 0])
      Grunt.inset($0, with: [.Top: 40])
    }
    
    label = Architect.label(inView: yellowView) { [unowned self] in
      Grunt.size($0, withExtendedOptions: [.Width: (.Equal, 80, .Required)])
      Grunt.construct(Blueprint.inset(edges: UIEdgeInsetsMake(10, 10, 10, 10), of: $0), inView: self.yellowView)
    }
    
    label.text = "Labels generated by Architect have numberOfLines = 0"
  }
}
